main:
  - name: ä¸»é¡µ
    title: é²¸äº‘ğŸ³
    pageRef: /
    weight: 1
  - name: åˆ†ç±»
    title: é²¸äº‘ğŸ³çš„åšå®¢
    pageRef: categories
    weight: 2
  - name: æ ‡ç­¾
    title: é²¸äº‘ğŸ³çš„åšå®¢
    pageRef: tags
    weight: 3
footer:
  - pre: github
    name: GitHub
    url: https://github.com/togally
    weight: 1