main:
  - name: ä¸»é¡µ
    title: é²¸äº‘ğŸ³
    pageRef: /
    weight: 1
  - name: åšå®¢
    title: é²¸äº‘ğŸ³çš„åšå®¢
    pageRef: series
    weight: 2
footer:
  - pre: github
    name: GitHub
    url: https://github.com/togally
    weight: 1