colorScheme: Blowfish
#logo: logo.jpeg
defaultAppearance: dark
enableSearch: true

author:
  name: "zhiwei.jia"
  image: "https://avatars.githubusercontent.com/u/33048626?s%E2%80%A600&u=2ee08ce248df82e6f5574483cfe812d9455f0f4a&v=4"
  headline: "为往圣继绝学"
  bio: "为往圣继绝学"
  links:
    - github: "https://github.com/togally"
    - zhihu: "https://www.zhihu.com/people/jzw-1-56"

homepage:
  layout: profile
  showRecent: false

header:
  layout: basic
  showAppearanceSwitcher: true

footer:
  showMenu: false
  showCopyright: true
  showThemeAttribution: false
  showAppearanceSwitcher: true
  showScrollToTop: true

list:
  showCards: true
  constrainItemsWidth: true
  showSummary: false
  showViews: false
  showLikes: false

article:
  showDate: false
  showViews: true
  showLikes: true
  showAuthor: true
  invertPagination: true
  showTableOfContents: true
  showTaxonomies: true
  showWordCount: false
  showZenMode: false

taxonomy:
  showSummary: true

term:
  showSummary: true
  showBreadcrumbs: false
  showViews: false
  showLikes: false
  showTableOfContents: true
  groupByYear: false
  cardView: false
  cardViewScreenWidth: false

firebase:
  apiKey: "AIzaSyA74i1CpEW8Dc-sCb6DV71DjLzClBGT9O0",
  authDomain: "blog-363315.firebaseapp.com"
  projectId: "blog-363315"
  storageBucket: "blog-363315.appspot.com"
  messagingSenderId: "1066744069356"
  appId: "1:1066744069356:web:3e396684750779aa8739c9"
  measurementId: "G-811FWCZ4B4"